services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    ports:
      - ${MOSQUITTO_MQTT_PORT:-1883}:1883
      - ${MOSQUITTO_WS_PORT:-9001}:9001
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  mosquitto_data:
  mosquitto_log:
