name: Auto Merge Release PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    steps:
      - name: Auto-merge release-please PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.RELEASE_PLEASE_TOKEN}}
        run: |
          # Note: We rely on GitHub branch protections/status checks passing before the merge actually occurs
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
